# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20170716_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='company',
            field=models.CharField(default=b'None', max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='first_name',
            field=models.CharField(default=b'', max_length=30),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(default=b'', max_length=30),
        ),
    ]
